### PR TITLE
Implement Task 3 (L)

### PR DESCRIPTION
**Pull request by KyleKing**
- [x] (WIP, This PR) Refactor to support a new `PlayerInventory` that is written by the user for Task 3
- [ ] (Next PR) Separate the lesson from the task. See code tag in `tasks.__init__`

### CODE REVIEW

**Comment by KyleKing** [comment]
Ok, I think the Task 3 is somewhat playable. The task only requires essentially removing the bad consumable function for now, but once we figure out the mechanism for crafting the raft, we can go back and improve it

Still probably a few things left to do before user testing

- [ ] Reorganize the files into separate lesson/task (is this a good idea?)
- [ ] Add a pinned message to indicate what the user should do? Or just have the test suite guide development? Right now, the `pft` fails for both task 1 and task 3 because it doesn't know not to test the latter until the first is complete, which I'm not sure how best to implement
- [ ] Anything else for this second iteration of testing?

**Review by dimmerex — COMMENTED** [review]
Task 3 is looking good, but noticed a few things:
- This is minor, but the item no longer gets added to the inventory immediately, it only gets added after the player moves. Is this intentional?
- Sometimes items aren't added to inventory correctly. For example, when the user cuts down the first tree, they get 2 wood, and when they cut down the second tree, they get 0 wood. Previously, each tree gives 1 wood.
- When the user reloads, the number of items in the inventory changes. The first slot increments by 1 while the other slots double.

Maybe some of these are related to the "bad consumable function"? I think it's unclear.

Regarding the open questions:
- Reorganize the files into separate lesson/task (is this a good idea?): Perhaps each task can have its own folder, so for example, the task0 folder would have a lesson and a task. I prefer that over having all lessons/tasks in one folder.
- Add a pinned message to indicate what the user should do? Or just have the test suite guide development?: For now, maybe we can use a message box (with a long duration) to indicate what task the user should do and ask the user to run `pft` after both tasks are complete. I did want to implement a pinned message but I think we decided to hold off on that for now?
- Anything else for this second iteration of testing? - Mainly just decided on what to do for the previous point

**Comment by KyleKing** [comment]
Thanks, it was actually only updating at most once per second because the inventory was only being updated on save, which I reduced to at most once per second. The last two commits fix updating the inventory on key release

The 0,2,4 is indexing is semi-intentional based on the method that needs to be replaced: https://github.com/DesignPatternsAdventure/game/pull/21/commits/b1bbe1cf4e781247821210361bbd143839beee81

I'm open to any better ideas! I was planning on refactoring the raft creation into this task, but I'm not quite sure how it would work and what would be a good small chunk of work. This is just a placeholder now so that the task could at least be user tested

On the message box, I was just referencing that we don't necessarily need that feature now, but we need some way to communicate and track the current task for the doit check and test to work properly

**Comment by KyleKing** [comment]
I went ahead and merged so that we can make the next batch of changes. I'm done for today, but I can reorganize the folder tomorrow and continue to think about the tasks and feedback tool

If you have any ideas or improvements, feel free to start making the changes!

**Comment by dimmerex** [comment]
@KyleKing 
> The 0,2,4 is indexing is semi-intentional based on the method that needs to be replaced: https://github.com/DesignPatternsAdventure/game/commit/b1bbe1cf4e781247821210361bbd143839beee81
Yeah I have tried to remove `ConsumableItem.increment_count` altogether but the inventory still increments on reload 🤔

**Comment by KyleKing** [comment]
Shoot, I think those were issues when I tried to extract the count logic from the user method. I'll try to fix those this morning

**Pull request merged**
