### PR TITLE
build: switch to requirements.txt

### PR DESCRIPTION
**Pull request by KyleKing**
I thought about `pyinstaller` (wouldn't actually work), Docker, and a few other options, but the real issue is both poetry and python that adds so much complexity when we can just suggest `requirements.txt` like our mentor mentioned

- [x] Update README
- [x] Update INSTALL.md (I still want to add a bit more explanation on how to install Python and make it easier to use for anyone who wants proper environments)
- [x] Add a video/gif of initial gameplay

### CODE REVIEW

**Comment by KyleKing** [comment]
USWNT lost, but made progress on the pip-based installation! I added a few gif's as well to show the game play and tooling that we should replace later on

**Comment by KyleKing** [comment]
Also, I'm pretty sure this wouldn't have been a problem with normal python, but `asdf` only maps `python` (and a select few others) to the path. As a workaround for the pip-based install using `asdf-installed` Python I did 😅 

```sh
alias doit=/Users/kyleking/.asdf/installs/python/3.10.5/bin/doit
```

I'm *pretty sure* this wouldn't be an issue for a normal Python install, but I vote for asking our mentor to test it! 😄

**Comment by dimmerex** [comment]
> I'm _pretty sure_ this wouldn't be an issue for a normal Python install, but I vote for asking our mentor to test it! 😄

I tested this in a virtualenv and it works! 😄

**Review by dimmerex — APPROVED** [review]
Tested and approved! Also the README looks great!

**Pull request merged**
